### ISSUE TITLE
Passing arguments to build targets

### ISSUE THREAD

**Issue by faxal** [magefile/mage#135] opened 2018-08-26 07:01 UTC
I'm unable to pass arguments to build targets. I have build targets that compiles differently based on arguments passed. 

It's not immediately obvious how to do it.

**Comment by faxal** [comment] 2018-08-26 08:58
I have gone through the source and if I understand correctly all arguments except few builtin ones are considered as targets?

**Comment by natefinch** [comment] 2018-08-26 11:07
Yep. There's an issue exploring getting mage to understand arguments.  It's
mostly a case of figuring out what we *want* to do and then implementing
it. The actual implementation isn't hard, it's making the tool intuitive.

The easiest work-around for now is to pass in arguments as environment
variables.  i.e

foo_var=bar mage build

I would like to eventually add argument support.  I just want to do it in a
way that isn't confusing or ambiguous.

**Comment by natefinch** [comment] 2018-08-31 19:13
Closing this as a dupe of #24.

**Closed by natefinch** 2018-08-31 19:13 UTC
