### ISSUE TITLE
`mage -version` does not return version information  

### ISSUE THREAD

**Issue by vassudanagunta** [magefile/mage#83] opened 2017-10-24 15:11 UTC
Currently the output of `mage -version` is:
```
Mage Build Tool 
Build Date: <not set>
Commit: <not set>
```

**Comment by vassudanagunta** [comment] 2017-10-24 15:13
Being able to see the version of mage one is invoking can help diagnose problems such as gohugoio/hugo#4003.  Also useful for filing bug reports.

**Comment by natefinch** [comment] 2017-10-24 17:46
Right now, mage -version is only populated if you use the binary version of mage, or if you build mage with `mage build`.  

There's no way to hard code the specific commit revision in the sourcecode, but I *could* hard code the major version number, which would at least give you an idea of what you're running.

**Comment by natefinch** [comment] 2017-10-25 01:49
fixed with #84

**Closed by natefinch** 2017-10-25 01:49 UTC

**Comment by galopin** [comment] 2017-10-25 10:00
> Right now, `mage -version` is only populated if […] you build mage with `mage build`.

```
$ go get -u -v github.com/magefile/mage
github.com/magefile/mage (download)
github.com/magefile/mage/types
github.com/magefile/mage/mg
github.com/magefile/mage/parse
github.com/magefile/mage/sh
github.com/magefile/mage/mage
github.com/magefile/mage

$ cd ~/Go/src/github.com/magefile/mage
$ mage build
$ mage -version
Mage Build Tool v2
Build Date: <not set>
Commit: <not set>
```

Build and commit fields are still unset ⁉️ But modification time of mage binary in `"${GOPATH}/bin"` hasn't changed a bit so I would suspect that something is not quite working as expected in the build process…

```
$ mage -v build
Running target: Build
exec: git rev-parse --short HEAD
exec: git describe --tags
exec: go install -ldflags=-X "github.com/magefile/mage/mage.timestamp=2017-10-25T11:21:46+02:00" -X "github.com/magefile/mage/mage.commitHash=ab3ca2f" -X "github.com/magefile/mage/mage.gitTag=v2.0.1" github.com/magefile/mage

$ git rev-parse --short HEAD
ab3ca2f

$ git describe --tags
v2.0.1

$ go install -ldflags=-X "github.com/magefile/mage/mage.timestamp=2017-10-25T11:21:46+02:00" -X "github.com/magefile/mage/mage.commitHash=ab3ca2f" -X "github.com/magefile/mage/mage.gitTag=v2.0.1" github.com/magefile/mage
can't load package: package github.com/magefile/mage/mage.timestamp=2017-10-25T11:21:46+02:00: cannot find package "github.com/magefile/mage/mage.timestamp=2017-10-25T11:21:46+02:00" in any of:
        C:\Go\src\github.com\magefile\mage\mage.timestamp=2017-10-25T11:21:46+02:00 (from $GOROOT)
        C:\Documents and Settings\Michaël\Go\src\github.com\magefile\mage\mage.timestamp=2017-10-25T11:21:46+02:00 (from $GOPATH)
can't load package: package -X: cannot find package "-X" in any of:
        C:\Go\src\-X (from $GOROOT)
        C:\Documents and Settings\Michaël\Go\src\-X (from $GOPATH)
can't load package: package github.com/magefile/mage/mage.commitHash=ab3ca2f: cannot find package "github.com/magefile/mage/mage.commitHash=ab3ca2f" in any of:
        C:\Go\src\github.com\magefile\mage\mage.commitHash=ab3ca2f (from $GOROOT)
        C:\Documents and Settings\Michaël\Go\src\github.com\magefile\mage\mage.commitHash=ab3ca2f (from $GOPATH)
can't load package: package github.com/magefile/mage/mage.gitTag=v2.0.1: cannot find package "github.com/magefile/mage/mage.gitTag=v2.0.1" in any of:
        C:\Go\src\github.com\magefile\mage\mage.gitTag=v2.0.1 (from $GOROOT)
        C:\Documents and Settings\Michaël\Go\src\github.com\magefile\mage\mage.gitTag=v2.0.1 (from $GOPATH)
```

Looks like there is a problem with the `-ldflags` param value [assignment](https://github.com/magefile/mage/blob/0eef6fef9dcfc72d5abe4b3ce4bdaf30c294039c/magefile.go#L22) 🐛

**Comment by galopin** [comment] 2017-10-25 10:15
Additionally shouldn't `mageVer` [be assigned](https://github.com/magefile/mage/blob/9d728eff80c7d83b290a2508c677950c183e52b6/mage/main.go#L29) the same value as `gitTag`?

```go
// mageVer is used when hashing the output binary to ensure that we get a new
// binary if we use a different version of mage.
const mageVer = "v0.3"
```

**Comment by natefinch** [comment] 2017-10-25 12:59
So, the problem is that go install turns into a no-op if the binary is already installed.  If you add "-a" to the list of args here: https://github.com/magefile/mage/blob/master/magefile.go#L22 . just after "install", then it should work correctly.  Sorry, that's a bug, I'll fix it.

Really though, we should stop using mage directly to build (since that's a chicken and egg problem), and instead use the [zero install option](https://magefile.org/zeroinstall/) with `go run` .... (and with the -a flag on go install).

**Comment by natefinch** [comment] 2017-10-25 13:02
The mageVer is poorly named and not documented well enough.  That's not really any kind of externally visible version number.  It's there simply to give us something to change to force mage to realize it needs to rebuild cached binaries, even if none of the input files have changed.  This could happen if there's a change in how we parse the files, but not in the output template for the generated main file, for example.

I'll fix the name and the comment, and probably next time I change it, I'll just make it a large ugly number, so it looks less like it should be a real version of something.

**Comment by galopin** [comment] 2017-10-25 13:31
1. Thank you very much for the tip about `go install -a …`. It does work indeed but still `timestamp`, `commitHash` and `gitTag` values are not properly set during the build process ⁉️ IMHO `-ldflags` param value is not properly assembled in [`magefile.go`](https://github.com/magefile/mage/blob/9d728eff80c7d83b290a2508c677950c183e52b6/magefile.go#L22) — please compare `go install -ldflags …` commands output below. 

```bash
$ go install -a -ldflags=-X "github.com/magefile/mage/mage.timestamp=2017-10-25T11:21:46+02:00" -X "github.com/magefile/mage/mage.commitHash=ab3ca2f" -X "github.com/magefile/mage/mage.gitTag=v2.0.1" github.com/magefile/mage
can't load package: package github.com/magefile/mage/mage.timestamp=2017-10-25T11:21:46+02:00: cannot find package "github.com/magefile/mage/mage.timestamp=2017-10-25T11:21:46+02:00" in any of:
        C:\Go\src\github.com\magefile\mage\mage.timestamp=2017-10-25T11:21:46+02:00 (from $GOROOT)
        C:\Documents and Settings\Michaël\Go\src\github.com\magefile\mage\mage.timestamp=2017-10-25T11:21:46+02:00 (from $GOPATH)
can't load package: package -X: cannot find package "-X" in any of:
        C:\Go\src\-X (from $GOROOT)
        C:\Documents and Settings\Michaël\Go\src\-X (from $GOPATH)
can't load package: package github.com/magefile/mage/mage.commitHash=ab3ca2f: cannot find package "github.com/magefile/mage/mage.commitHash=ab3ca2f" in any of:
        C:\Go\src\github.com\magefile\mage\mage.commitHash=ab3ca2f (from $GOROOT)
        C:\Documents and Settings\Michaël\Go\src\github.com\magefile\mage\mage.commitHash=ab3ca2f (from $GOPATH)
can't load package: package github.com/magefile/mage/mage.gitTag=v2.0.1: cannot find package "github.com/magefile/mage/mage.gitTag=v2.0.1" in any of:
        C:\Go\src\github.com\magefile\mage\mage.gitTag=v2.0.1 (from $GOROOT)
        C:\Documents and Settings\Michaël\Go\src\github.com\magefile\mage\mage.gitTag=v2.0.1 (from $GOPATH)

$ echo $?
1

## failure
```

vs.

```bash
$ go install -a -ldflags "-X github.com/magefile/mage/mage/main.timestamp=2017-10-25T11:21:46+02:00 -X github.com/magefile/mage/mage/main.commitHash=ab3ca2f -X github.com/magefile/mage/mage/main.gitTag=v2.0.1" github.com/magefile/mage

$ echo $?
0

$ mage -version
Mage Build Tool v2
Build Date: <not set>
Commit: <not set>

## success… well, sort of
```

2. So `mageVer` is kind of a magic number. Got it, thank you!

**Comment by natefinch** [comment] 2017-10-25 13:54
ldflags are really annoying to type in a terminal, part of why I use a script :) 
Your first example isn't quoted correctly. The whole -x foo -x bar needs to be in quotes after the ldflags= . Your second example uses github.com/magefile/mage/mage/main.foo which is not the right path (github.com/magefile/mage/mage/main is not a valid package)

What you want is this:

```
$ go install -a -ldflags='-X "github.com/magefile/mage/mage.timestamp=2017-10-25T11:21:46+02:00" -X "github.com/magefile/mage/mage.commitHash=ab3ca2f" -X "github.com/magefile/mage/mage.gitTag=v2.0.1"' github.com/magefile/mage

$ mage -version
Mage Build Tool v2.0.1
Build Date: 2017-10-25T11:21:46+02:00
Commit: ab3ca2f
```

**Comment by natefinch** [comment] 2017-10-25 14:12
I just merged a change that'll make the `mage build` target use -a, so it'll do the right thing. There's also now better installation instructions, and a bootstrap.go file that you can `go run` for first time users that don't have mage yet.

Thanks for reporting this, you've made the first-time experience a lot better because of it :)

**Comment by galopin** [comment] 2017-10-25 15:00
> ldflags are really annoying to type in a terminal, part of why I use a script :)

Oops, I stand corrected. Sorry for the wrong package path in the second example provided. It does work 😄 

```bash
$ go install -a -ldflags "-X github.com/magefile/mage/mage.timestamp=2017-10-25T11:21:46+02:00 -X github.com/magefile/mage/mage.commitHash=ab3ca2f -X github.com/magefile/mage/mage.gitTag=v2.0.1" github.com/magefile/mage

$ echo $?
0

$ mage -version
Mage Build Tool v2.0.1
Build Date: 2017-10-25T11:21:46+02:00
Commit: ab3ca2f
```

The `go install`command in the first example was reproduced "as is" from a `mage -v build` output , hence the missing enclosing quotes ⁉️ Also please notice that `gitTag` value might end with a newline character.

```
$ mage -v build
Running target: Build
exec: git rev-parse --short HEAD
exec: git describe --tags
exec: go install -ldflags=-X "github.com/magefile/mage/mage.timestamp=2017-10-25T16:49:37+02:00" -X "github.com/magefile/mage/mage.commitHash=ab3ca2f" -X "github.com/magefile/mage/mage.gitTag=v2.0.1
" github.com/magefile/mage
```

**Comment by galopin** [comment] 2017-10-25 15:27
```
$ go get -u -d github.com/magefile/mage
$ cd ~/Go/src/github.com/magefile/mage
$ go run bootstrap.go
Running target: Build
exec: git rev-parse --short HEAD
exec: git describe --tags
exec: go install -a -ldflags=-X "github.com/magefile/mage/mage.timestamp=2017-10-25T17:08:08+02:00" -X "github.com/magefile/mage/mage.commitHash=58812e2" -X "github.com/magefile/mage/mage.gitTag=v2.0.1-1
-g58812e2
" github.com/magefile/mage

$ mage -version
Mage Build Tool v2.0.1-1-g58812e2

Build Date: 2017-10-25T17:18:04+02:00
Commit: 58812e2
```
Thumbs up! You may need to [chomp](http://perldoc.perl.org/functions/chomp.html) the `gitTag` value though 😉

**Comment by natefinch** [comment] 2017-10-25 15:31
So, the mage output is not shell quoted. Running commands from Go does not use a shell, it runs the binary executable and passes arguments directly to it.  Thus, it doesn't need to worry about quoting problems (this is really handy).  Each string in the list of arguments sent to `exec.Command` (or in our case, `sh.RunV`) is a complete argument for the command.

But this does mean that when you print out the commands, they're not shell quoted correctly.  I could probably fix that by printing out the arguments with %q which would escape quotes etc. It might not be 100% shell quoted, but it would be closer.

You're right about the line return from git tag... and if I was using `sh.Output`, it would strip that line return, but for some reason it's using `sh.Exec` which (intentionally) doesn't do that.... I don't know why I made it use sh.Exec instead of output... I think because at one point I was doing something more fancy, and now I'm not.  I'll fix that in the next change I check in.  Thanks for pinging me about it.

**Comment by galopin** [comment] 2017-10-25 15:51
You're welcome.Thank you for your thorough explanations and for not jumping down my throat when I was making glaring mistakes and therefore false assumptions. Source code may look like C (or Perl) but obviously I need to strengthen my Go programming skills 😃

**Comment by natefinch** [comment] 2017-10-25 17:03
no worries at all.  I can't tell you how long it took me to get the ldflags right, precisely because of shell quoting (or not), and all that.  You're essentially double-quoting everything because it gets passed to a different tool later on... it's crazy.

**Comment by whoisjake** [comment] 2017-10-27 14:49
FWIW: https://github.com/magefile/mage/issues/88

I think it's related to this
