### ISSUE TITLE
Do a better job recognizing when magefile.go changes

### ISSUE THREAD

**Issue by mcandre** [magefile/mage#114] opened 2018-03-31 23:20 UTC
mage often continues executing old build scripts after `magefile.go` has changed. Please do a better job identifying when this occurs, such as recording the modification time and/or hash of magefiles.

As a workaround, I am manually running `mage -clean` to force mage to recompile my magefiles.

**Comment by natefinch** [comment] 2018-05-25 13:53
So, mage does record a hash of all magefiles as a part of determining whether it needs to rebuild the binary.  Where this can fall down is if you make changes to an external package with no changes to the magefiles in the current directory.

I'll have to look into the new code in 1.10 for recognizing when build parameters change to see if I can leverage that to determine when a rebuild is needed.

**Comment by natefinch** [comment] 2018-07-16 20:02
Let me know if you can reproduce this behavior, since it is important to me that the magefile changing definitely should cause a rebuild of the mage cached binary.

**Comment by andrewkroh** [comment] 2018-08-01 14:35
It definitely would be nice to be able to detect changes to the imported dependency tree of `magefile.go`.

In an effort to avoid code duplication between multiple `magefile.go` files I have moved common code to its own package and import this in each `magefile.go`. When changes are made to the common code this can break things for other developers on the project until they `mage -clean` in there local development environment.

**Comment by natefinch** [comment] 2018-08-01 17:38
Yes, that's a very good point.  I wonder if the updates in 1.10 to detecting changes in code could be used by mage instead of my custom code.  I'll have to take a look.  Another option might be to add an environment variable to tell Mage to always rebuild.

**Comment by natefinch** [comment] 2018-09-18 14:12
I have a PR up that will address this if you're compiling with 1.10 or higher.  It needs a few tests, but otherwise should be good to go.

**Comment by natefinch** [comment] 2018-09-19 03:06
Fixed in #168

**Closed by natefinch** 2018-09-19 03:06 UTC
Labels: maybe-bug
