### ISSUE TITLE
mg.Deps and anonymous functions

### ISSUE THREAD

**Issue by wrouesnel** [magefile/mage#107] opened 2018-02-25 21:27 UTC
`mg.Deps()` doesn't seem to handle anonymous functions properly. Given a loop like below:
```go
func Demo() error {
	cmds := []interface{}{}
	for i:=0; i < 10; i++ {
		k := i
		f := func() error {
			fmt.Println(k)
			return nil
		}
		cmds = append(cmds, f)
	}
	mg.Deps(cmds...)
	return nil
}
```
I get the following output:
```
Running target: Demo
0
```
I ran into this while generating dynamic build targets for a multi-platform build (to give a use case).

**Comment by natefinch** [comment] 2018-02-25 21:38
Yeah, I've seen similar problems.  I'll try to work out a fix, but it's a
little tricky.  Basically, I need a unique identifier for each function, to
know if I'm running the same one more than once, and generated functions
like this confuse it.

There's a work around - make a function that calls the list of generated
functions, and then that function can be the dependency.

**Comment by wrouesnel** [comment] 2018-02-26 13:15
Seems like the pointer value of the function should serve? In this case each generated function definitely has a unique memory address - I don't *think* the same function should be able to appear without one?

**Comment by natefinch** [comment] 2018-09-12 20:34
closing this as a dupe of #101

**Closed by natefinch** 2018-09-12 20:34 UTC
Labels: duplicate, future-maybe
